<?xml version="1.0"?>
<robot name="quadcopter" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- ==================== PROPERTIES ==================== -->
  <xacro:property name="body_mass" value="1.5"/>
  <xacro:property name="body_radius" value="0.25"/>
  <xacro:property name="body_height" value="0.1"/>
  <xacro:property name="arm_length" value="0.25"/>
  <xacro:property name="arm_radius" value="0.02"/>
  <xacro:property name="rotor_radius" value="0.1"/>
  <xacro:property name="rotor_height" value="0.01"/>
  <xacro:property name="rotor_mass" value="0.05"/>

  <!-- ==================== MATERIALS ==================== -->
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>
  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.1 0.1 1"/>
  </material>

  <!-- ==================== BASE LINK ==================== -->
  <link name="base_link">
    <inertial>
      <mass value="${body_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.029" ixy="0" ixz="0" iyy="0.029" iyz="0" izz="0.055"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- ==================== ARM MACRO ==================== -->
  <xacro:macro name="arm" params="name angle">
    <link name="${name}_arm">
      <inertial>
        <mass value="0.05"/>
        <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
      <visual>
        <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_length}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_arm_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${name}_arm"/>
      <origin xyz="0 0 0" rpy="0 0 ${angle}"/>
    </joint>

    <link name="${name}_rotor">
      <inertial>
        <mass value="${rotor_mass}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0002"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${rotor_radius}" length="${rotor_height}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${rotor_radius}" length="${rotor_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_rotor_joint" type="fixed">
      <parent link="${name}_arm"/>
      <child link="${name}_rotor"/>
      <origin xyz="${arm_length} 0 0.03" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Create 4 arms at 45, 135, 225, 315 degrees -->
  <xacro:arm name="front_right" angle="${-pi/4}"/>
  <xacro:arm name="front_left" angle="${pi/4}"/>
  <xacro:arm name="rear_left" angle="${3*pi/4}"/>
  <xacro:arm name="rear_right" angle="${-3*pi/4}"/>

  <!-- ==================== CAMERA SENSOR ==================== -->
  <link name="camera_link">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.08 0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.08 0.03"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${body_radius + 0.02} 0 -0.02" rpy="0 0.2 0"/>
  </joint>

  <link name="camera_optical_frame"/>
  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- Camera Gazebo Plugin -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="front_camera">
      <update_rate>30.0</update_rate>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <camera name="front_camera">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>100</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>30.0</updateRate>
        <cameraName>camera</cameraName>
        <imageTopicName>rgb/image_raw</imageTopicName>
        <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
        <frameName>camera_optical_frame</frameName>
        <hackBaseline>0.0</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>

  <!-- ==================== LIDAR SENSOR ==================== -->
  <link name="lidar_link">
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <!-- LIDAR positioned at front of drone, ahead of legs -->
    <!-- X = body_radius (0.25) + 0.10m offset = 0.35m forward -->
    <origin xyz="${body_radius + 0.10} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- 2D LiDAR Gazebo Plugin (Front 180 degree scan) -->
  <gazebo reference="lidar_link">
    <sensor type="ray" name="lidar_sensor">
      <always_on>true</always_on>
      <update_rate>15.0</update_rate>
      <visualize>true</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>120</samples>
            <resolution>1</resolution>
            <!-- Front 120 degrees: -60 to +60 degrees (avoids propellers at ±45°) -->
            <min_angle>-1.0472</min_angle>
            <max_angle>1.0472</max_angle>
          </horizontal>
        </scan>
        <range>
          <!-- Min 0.50m to filter out any drone body/propeller readings -->
          <min>0.50</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="lidar_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- ==================== IMU SENSOR ==================== -->
  <link name="imu_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <gazebo reference="imu_link">
    <sensor type="imu" name="imu_sensor">
      <always_on>true</always_on>
      <update_rate>100.0</update_rate>
      <visualize>false</visualize>
      <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
        <topicName>/imu/data</topicName>
        <bodyName>imu_link</bodyName>
        <updateRateHZ>100.0</updateRateHZ>
        <gaussianNoise>0.01</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- ==================== GAZEBO MATERIAL COLORS ==================== -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="front_right_arm">
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="front_left_arm">
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="rear_left_arm">
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="rear_right_arm">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <gazebo reference="front_right_rotor">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="front_left_rotor">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="rear_left_rotor">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="rear_right_rotor">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="camera_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="lidar_link">
    <material>Gazebo/Blue</material>
  </gazebo>

</robot>
